USE web_database;
CREATE INDEX idx_users_role            ON users(role);
CREATE INDEX idx_thesis_topics_creator ON thesis_topics(created_by);
CREATE INDEX idx_thesis_topics_active  ON thesis_topics(is_active);
CREATE INDEX idx_theses_topic          ON theses(topic_id);
CREATE INDEX idx_theses_student        ON theses(student_id);
CREATE INDEX idx_theses_supervisor     ON theses(supervisor_id);
CREATE INDEX idx_theses_status         ON theses(status);
CREATE INDEX idx_ci_thesis             ON committee_invitations(thesis_id);
CREATE INDEX idx_ci_faculty_status     ON committee_invitations(invitee_id, response);
CREATE INDEX idx_cm_thesis             ON committee_members(thesis_id);
CREATE INDEX idx_cm_faculty            ON committee_members(faculty_id);
CREATE UNIQUE INDEX uq_cm_thesis_faculty ON committee_members(thesis_id, faculty_id);
CREATE UNIQUE INDEX uq_grades_thesis_grader ON grades(thesis_id, grader_id);
CREATE INDEX idx_notes_thesis_author   ON notes(thesis_id, author_id);
CREATE INDEX idx_grades_thesis_grader  ON grades(thesis_id, grader_id);
CREATE INDEX idx_sh_thesis_to          ON status_history(thesis_id, to_status);
CREATE INDEX idx_sh_changed            ON status_history(thesis_id, changed_at);
CREATE INDEX idx_pa_sched              ON presentation_announcements(scheduled_at);
CREATE INDEX idx_pa_thesis             ON presentation_announcements(thesis_id);
